# -*- coding: utf-8 -*-
#
# TARGET arch is: []
# WORD_SIZE is: 8
# POINTER_SIZE is: 8
# LONGDOUBLE_SIZE is: 16
#
import ctypes




LINUX_PCI_REGS_H = True # macro
PCI_VENDOR_ID = 0x00 # macro
PCI_DEVICE_ID = 0x02 # macro
PCI_COMMAND = 0x04 # macro
PCI_COMMAND_IO = 0x1 # macro
PCI_COMMAND_MEMORY = 0x2 # macro
PCI_COMMAND_MASTER = 0x4 # macro
PCI_COMMAND_SPECIAL = 0x8 # macro
PCI_COMMAND_INVALIDATE = 0x10 # macro
PCI_COMMAND_VGA_PALETTE = 0x20 # macro
PCI_COMMAND_PARITY = 0x40 # macro
PCI_COMMAND_WAIT = 0x80 # macro
PCI_COMMAND_SERR = 0x100 # macro
PCI_COMMAND_FAST_BACK = 0x200 # macro
PCI_COMMAND_INTX_DISABLE = 0x400 # macro
PCI_STATUS = 0x06 # macro
PCI_STATUS_INTERRUPT = 0x08 # macro
PCI_STATUS_CAP_LIST = 0x10 # macro
PCI_STATUS_66MHZ = 0x20 # macro
PCI_STATUS_UDF = 0x40 # macro
PCI_STATUS_FAST_BACK = 0x80 # macro
PCI_STATUS_PARITY = 0x100 # macro
PCI_STATUS_DEVSEL_MASK = 0x600 # macro
PCI_STATUS_DEVSEL_FAST = 0x000 # macro
PCI_STATUS_DEVSEL_MEDIUM = 0x200 # macro
PCI_STATUS_DEVSEL_SLOW = 0x400 # macro
PCI_STATUS_SIG_TARGET_ABORT = 0x800 # macro
PCI_STATUS_REC_TARGET_ABORT = 0x1000 # macro
PCI_STATUS_REC_MASTER_ABORT = 0x2000 # macro
PCI_STATUS_SIG_SYSTEM_ERROR = 0x4000 # macro
PCI_STATUS_DETECTED_PARITY = 0x8000 # macro
PCI_CLASS_REVISION = 0x08 # macro
PCI_REVISION_ID = 0x08 # macro
PCI_CLASS_PROG = 0x09 # macro
PCI_CLASS_DEVICE = 0x0a # macro
PCI_CACHE_LINE_SIZE = 0x0c # macro
PCI_LATENCY_TIMER = 0x0d # macro
PCI_HEADER_TYPE = 0x0e # macro
PCI_HEADER_TYPE_NORMAL = 0 # macro
PCI_HEADER_TYPE_BRIDGE = 1 # macro
PCI_HEADER_TYPE_CARDBUS = 2 # macro
PCI_BIST = 0x0f # macro
PCI_BIST_CODE_MASK = 0x0f # macro
PCI_BIST_START = 0x40 # macro
PCI_BIST_CAPABLE = 0x80 # macro
PCI_BASE_ADDRESS_0 = 0x10 # macro
PCI_BASE_ADDRESS_1 = 0x14 # macro
PCI_BASE_ADDRESS_2 = 0x18 # macro
PCI_BASE_ADDRESS_3 = 0x1c # macro
PCI_BASE_ADDRESS_4 = 0x20 # macro
PCI_BASE_ADDRESS_5 = 0x24 # macro
PCI_BASE_ADDRESS_SPACE = 0x01 # macro
PCI_BASE_ADDRESS_SPACE_IO = 0x01 # macro
PCI_BASE_ADDRESS_SPACE_MEMORY = 0x00 # macro
PCI_BASE_ADDRESS_MEM_TYPE_MASK = 0x06 # macro
PCI_BASE_ADDRESS_MEM_TYPE_32 = 0x00 # macro
PCI_BASE_ADDRESS_MEM_TYPE_1M = 0x02 # macro
PCI_BASE_ADDRESS_MEM_TYPE_64 = 0x04 # macro
PCI_BASE_ADDRESS_MEM_PREFETCH = 0x08 # macro
PCI_BASE_ADDRESS_MEM_MASK = (~0x0f) # macro
PCI_BASE_ADDRESS_IO_MASK = (~0x03) # macro
PCI_CARDBUS_CIS = 0x28 # macro
PCI_SUBSYSTEM_VENDOR_ID = 0x2c # macro
PCI_SUBSYSTEM_ID = 0x2e # macro
PCI_ROM_ADDRESS = 0x30 # macro
PCI_ROM_ADDRESS_ENABLE = 0x01 # macro
PCI_ROM_ADDRESS_MASK = (~0x7ff) # macro
PCI_CAPABILITY_LIST = 0x34 # macro
PCI_INTERRUPT_LINE = 0x3c # macro
PCI_INTERRUPT_PIN = 0x3d # macro
PCI_MIN_GNT = 0x3e # macro
PCI_MAX_LAT = 0x3f # macro
PCI_PRIMARY_BUS = 0x18 # macro
PCI_SECONDARY_BUS = 0x19 # macro
PCI_SUBORDINATE_BUS = 0x1a # macro
PCI_SEC_LATENCY_TIMER = 0x1b # macro
PCI_IO_BASE = 0x1c # macro
PCI_IO_LIMIT = 0x1d # macro
PCI_IO_RANGE_TYPE_MASK = 0x0f # macro
PCI_IO_RANGE_TYPE_16 = 0x00 # macro
PCI_IO_RANGE_TYPE_32 = 0x01 # macro
PCI_IO_RANGE_MASK = (~0x0f) # macro
PCI_SEC_STATUS = 0x1e # macro
PCI_MEMORY_BASE = 0x20 # macro
PCI_MEMORY_LIMIT = 0x22 # macro
PCI_MEMORY_RANGE_TYPE_MASK = 0x0f # macro
PCI_MEMORY_RANGE_MASK = (~0x0f) # macro
PCI_PREF_MEMORY_BASE = 0x24 # macro
PCI_PREF_MEMORY_LIMIT = 0x26 # macro
PCI_PREF_RANGE_TYPE_MASK = 0x0f # macro
PCI_PREF_RANGE_TYPE_32 = 0x00 # macro
PCI_PREF_RANGE_TYPE_64 = 0x01 # macro
PCI_PREF_RANGE_MASK = (~0x0f) # macro
PCI_PREF_BASE_UPPER32 = 0x28 # macro
PCI_PREF_LIMIT_UPPER32 = 0x2c # macro
PCI_IO_BASE_UPPER16 = 0x30 # macro
PCI_IO_LIMIT_UPPER16 = 0x32 # macro
PCI_ROM_ADDRESS1 = 0x38 # macro
PCI_BRIDGE_CONTROL = 0x3e # macro
PCI_BRIDGE_CTL_PARITY = 0x01 # macro
PCI_BRIDGE_CTL_SERR = 0x02 # macro
PCI_BRIDGE_CTL_ISA = 0x04 # macro
PCI_BRIDGE_CTL_VGA = 0x08 # macro
PCI_BRIDGE_CTL_MASTER_ABORT = 0x20 # macro
PCI_BRIDGE_CTL_BUS_RESET = 0x40 # macro
PCI_BRIDGE_CTL_FAST_BACK = 0x80 # macro
PCI_CB_CAPABILITY_LIST = 0x14 # macro
PCI_CB_SEC_STATUS = 0x16 # macro
PCI_CB_PRIMARY_BUS = 0x18 # macro
PCI_CB_CARD_BUS = 0x19 # macro
PCI_CB_SUBORDINATE_BUS = 0x1a # macro
PCI_CB_LATENCY_TIMER = 0x1b # macro
PCI_CB_MEMORY_BASE_0 = 0x1c # macro
PCI_CB_MEMORY_LIMIT_0 = 0x20 # macro
PCI_CB_MEMORY_BASE_1 = 0x24 # macro
PCI_CB_MEMORY_LIMIT_1 = 0x28 # macro
PCI_CB_IO_BASE_0 = 0x2c # macro
PCI_CB_IO_BASE_0_HI = 0x2e # macro
PCI_CB_IO_LIMIT_0 = 0x30 # macro
PCI_CB_IO_LIMIT_0_HI = 0x32 # macro
PCI_CB_IO_BASE_1 = 0x34 # macro
PCI_CB_IO_BASE_1_HI = 0x36 # macro
PCI_CB_IO_LIMIT_1 = 0x38 # macro
PCI_CB_IO_LIMIT_1_HI = 0x3a # macro
PCI_CB_IO_RANGE_MASK = (~0x03) # macro
PCI_CB_BRIDGE_CONTROL = 0x3e # macro
PCI_CB_BRIDGE_CTL_PARITY = 0x01 # macro
PCI_CB_BRIDGE_CTL_SERR = 0x02 # macro
PCI_CB_BRIDGE_CTL_ISA = 0x04 # macro
PCI_CB_BRIDGE_CTL_VGA = 0x08 # macro
PCI_CB_BRIDGE_CTL_MASTER_ABORT = 0x20 # macro
PCI_CB_BRIDGE_CTL_CB_RESET = 0x40 # macro
PCI_CB_BRIDGE_CTL_16BIT_INT = 0x80 # macro
PCI_CB_BRIDGE_CTL_PREFETCH_MEM0 = 0x100 # macro
PCI_CB_BRIDGE_CTL_PREFETCH_MEM1 = 0x200 # macro
PCI_CB_BRIDGE_CTL_POST_WRITES = 0x400 # macro
PCI_CB_SUBSYSTEM_VENDOR_ID = 0x40 # macro
PCI_CB_SUBSYSTEM_ID = 0x42 # macro
PCI_CB_LEGACY_MODE_BASE = 0x44 # macro
PCI_CAP_LIST_ID = 0 # macro
PCI_CAP_ID_PM = 0x01 # macro
PCI_CAP_ID_AGP = 0x02 # macro
PCI_CAP_ID_VPD = 0x03 # macro
PCI_CAP_ID_SLOTID = 0x04 # macro
PCI_CAP_ID_MSI = 0x05 # macro
PCI_CAP_ID_CHSWP = 0x06 # macro
PCI_CAP_ID_PCIX = 0x07 # macro
PCI_CAP_ID_HT = 0x08 # macro
PCI_CAP_ID_VNDR = 0x09 # macro
PCI_CAP_ID_DBG = 0x0A # macro
PCI_CAP_ID_CCRC = 0x0B # macro
PCI_CAP_ID_SHPC = 0x0C # macro
PCI_CAP_ID_SSVID = 0x0D # macro
PCI_CAP_ID_AGP3 = 0x0E # macro
PCI_CAP_ID_EXP = 0x10 # macro
PCI_CAP_ID_MSIX = 0x11 # macro
PCI_CAP_ID_AF = 0x13 # macro
PCI_CAP_LIST_NEXT = 1 # macro
PCI_CAP_FLAGS = 2 # macro
PCI_CAP_SIZEOF = 4 # macro
PCI_PM_PMC = 2 # macro
PCI_PM_CAP_VER_MASK = 0x0007 # macro
PCI_PM_CAP_PME_CLOCK = 0x0008 # macro
PCI_PM_CAP_RESERVED = 0x0010 # macro
PCI_PM_CAP_DSI = 0x0020 # macro
PCI_PM_CAP_AUX_POWER = 0x01C0 # macro
PCI_PM_CAP_D1 = 0x0200 # macro
PCI_PM_CAP_D2 = 0x0400 # macro
PCI_PM_CAP_PME = 0x0800 # macro
PCI_PM_CAP_PME_MASK = 0xF800 # macro
PCI_PM_CAP_PME_D0 = 0x0800 # macro
PCI_PM_CAP_PME_D1 = 0x1000 # macro
PCI_PM_CAP_PME_D2 = 0x2000 # macro
PCI_PM_CAP_PME_D3 = 0x4000 # macro
PCI_PM_CAP_PME_D3cold = 0x8000 # macro
PCI_PM_CAP_PME_SHIFT = 11 # macro
PCI_PM_CTRL = 4 # macro
PCI_PM_CTRL_STATE_MASK = 0x0003 # macro
PCI_PM_CTRL_NO_SOFT_RESET = 0x0008 # macro
PCI_PM_CTRL_PME_ENABLE = 0x0100 # macro
PCI_PM_CTRL_DATA_SEL_MASK = 0x1e00 # macro
PCI_PM_CTRL_DATA_SCALE_MASK = 0x6000 # macro
PCI_PM_CTRL_PME_STATUS = 0x8000 # macro
PCI_PM_PPB_EXTENSIONS = 6 # macro
PCI_PM_PPB_B2_B3 = 0x40 # macro
PCI_PM_BPCC_ENABLE = 0x80 # macro
PCI_PM_DATA_REGISTER = 7 # macro
PCI_PM_SIZEOF = 8 # macro
PCI_AGP_VERSION = 2 # macro
PCI_AGP_RFU = 3 # macro
PCI_AGP_STATUS = 4 # macro
PCI_AGP_STATUS_RQ_MASK = 0xff000000 # macro
PCI_AGP_STATUS_SBA = 0x0200 # macro
PCI_AGP_STATUS_64BIT = 0x0020 # macro
PCI_AGP_STATUS_FW = 0x0010 # macro
PCI_AGP_STATUS_RATE4 = 0x0004 # macro
PCI_AGP_STATUS_RATE2 = 0x0002 # macro
PCI_AGP_STATUS_RATE1 = 0x0001 # macro
PCI_AGP_COMMAND = 8 # macro
PCI_AGP_COMMAND_RQ_MASK = 0xff000000 # macro
PCI_AGP_COMMAND_SBA = 0x0200 # macro
PCI_AGP_COMMAND_AGP = 0x0100 # macro
PCI_AGP_COMMAND_64BIT = 0x0020 # macro
PCI_AGP_COMMAND_FW = 0x0010 # macro
PCI_AGP_COMMAND_RATE4 = 0x0004 # macro
PCI_AGP_COMMAND_RATE2 = 0x0002 # macro
PCI_AGP_COMMAND_RATE1 = 0x0001 # macro
PCI_AGP_SIZEOF = 12 # macro
PCI_VPD_ADDR = 2 # macro
PCI_VPD_ADDR_MASK = 0x7fff # macro
PCI_VPD_ADDR_F = 0x8000 # macro
PCI_VPD_DATA = 4 # macro
PCI_SID_ESR = 2 # macro
PCI_SID_ESR_NSLOTS = 0x1f # macro
PCI_SID_ESR_FIC = 0x20 # macro
PCI_SID_CHASSIS_NR = 3 # macro
PCI_MSI_FLAGS = 2 # macro
PCI_MSI_FLAGS_64BIT = 0x80 # macro
PCI_MSI_FLAGS_QSIZE = 0x70 # macro
PCI_MSI_FLAGS_QMASK = 0x0e # macro
PCI_MSI_FLAGS_ENABLE = 0x01 # macro
PCI_MSI_FLAGS_MASKBIT = 0x100 # macro
PCI_MSI_RFU = 3 # macro
PCI_MSI_ADDRESS_LO = 4 # macro
PCI_MSI_ADDRESS_HI = 8 # macro
PCI_MSI_DATA_32 = 8 # macro
PCI_MSI_MASK_32 = 12 # macro
PCI_MSI_DATA_64 = 12 # macro
PCI_MSI_MASK_64 = 16 # macro
PCI_MSIX_FLAGS = 2 # macro
PCI_MSIX_FLAGS_QSIZE = 0x7FF # macro
PCI_MSIX_FLAGS_ENABLE = (1<<15) # macro
PCI_MSIX_FLAGS_MASKALL = (1<<14) # macro
PCI_MSIX_FLAGS_BIRMASK = (7<<0) # macro
PCI_CHSWP_CSR = 2 # macro
PCI_CHSWP_DHA = 0x01 # macro
PCI_CHSWP_EIM = 0x02 # macro
PCI_CHSWP_PIE = 0x04 # macro
PCI_CHSWP_LOO = 0x08 # macro
PCI_CHSWP_PI = 0x30 # macro
PCI_CHSWP_EXT = 0x40 # macro
PCI_CHSWP_INS = 0x80 # macro
PCI_AF_LENGTH = 2 # macro
PCI_AF_CAP = 3 # macro
PCI_AF_CAP_TP = 0x01 # macro
PCI_AF_CAP_FLR = 0x02 # macro
PCI_AF_CTRL = 4 # macro
PCI_AF_CTRL_FLR = 0x01 # macro
PCI_AF_STATUS = 5 # macro
PCI_AF_STATUS_TP = 0x01 # macro
PCI_X_CMD = 2 # macro
PCI_X_CMD_DPERR_E = 0x0001 # macro
PCI_X_CMD_ERO = 0x0002 # macro
PCI_X_CMD_READ_512 = 0x0000 # macro
PCI_X_CMD_READ_1K = 0x0004 # macro
PCI_X_CMD_READ_2K = 0x0008 # macro
PCI_X_CMD_READ_4K = 0x000c # macro
PCI_X_CMD_MAX_READ = 0x000c # macro
PCI_X_CMD_SPLIT_1 = 0x0000 # macro
PCI_X_CMD_SPLIT_2 = 0x0010 # macro
PCI_X_CMD_SPLIT_3 = 0x0020 # macro
PCI_X_CMD_SPLIT_4 = 0x0030 # macro
PCI_X_CMD_SPLIT_8 = 0x0040 # macro
PCI_X_CMD_SPLIT_12 = 0x0050 # macro
PCI_X_CMD_SPLIT_16 = 0x0060 # macro
PCI_X_CMD_SPLIT_32 = 0x0070 # macro
PCI_X_CMD_MAX_SPLIT = 0x0070 # macro
def PCI_X_CMD_VERSION(x):  # macro
   return (((x)>>12)&3)  
PCI_X_STATUS = 4 # macro
PCI_X_STATUS_DEVFN = 0x000000ff # macro
PCI_X_STATUS_BUS = 0x0000ff00 # macro
PCI_X_STATUS_64BIT = 0x00010000 # macro
PCI_X_STATUS_133MHZ = 0x00020000 # macro
PCI_X_STATUS_SPL_DISC = 0x00040000 # macro
PCI_X_STATUS_UNX_SPL = 0x00080000 # macro
PCI_X_STATUS_COMPLEX = 0x00100000 # macro
PCI_X_STATUS_MAX_READ = 0x00600000 # macro
PCI_X_STATUS_MAX_SPLIT = 0x03800000 # macro
PCI_X_STATUS_MAX_CUM = 0x1c000000 # macro
PCI_X_STATUS_SPL_ERR = 0x20000000 # macro
PCI_X_STATUS_266MHZ = 0x40000000 # macro
PCI_X_STATUS_533MHZ = 0x80000000 # macro
PCI_EXP_FLAGS = 2 # macro
PCI_EXP_FLAGS_VERS = 0x000f # macro
PCI_EXP_FLAGS_TYPE = 0x00f0 # macro
PCI_EXP_TYPE_ENDPOINT = 0x0 # macro
PCI_EXP_TYPE_LEG_END = 0x1 # macro
PCI_EXP_TYPE_ROOT_PORT = 0x4 # macro
PCI_EXP_TYPE_UPSTREAM = 0x5 # macro
PCI_EXP_TYPE_DOWNSTREAM = 0x6 # macro
PCI_EXP_TYPE_PCI_BRIDGE = 0x7 # macro
PCI_EXP_TYPE_RC_END = 0x9 # macro
PCI_EXP_TYPE_RC_EC = 0x10 # macro
PCI_EXP_FLAGS_SLOT = 0x0100 # macro
PCI_EXP_FLAGS_IRQ = 0x3e00 # macro
PCI_EXP_DEVCAP = 4 # macro
PCI_EXP_DEVCAP_PAYLOAD = 0x07 # macro
PCI_EXP_DEVCAP_PHANTOM = 0x18 # macro
PCI_EXP_DEVCAP_EXT_TAG = 0x20 # macro
PCI_EXP_DEVCAP_L0S = 0x1c0 # macro
PCI_EXP_DEVCAP_L1 = 0xe00 # macro
PCI_EXP_DEVCAP_ATN_BUT = 0x1000 # macro
PCI_EXP_DEVCAP_ATN_IND = 0x2000 # macro
PCI_EXP_DEVCAP_PWR_IND = 0x4000 # macro
PCI_EXP_DEVCAP_RBER = 0x8000 # macro
PCI_EXP_DEVCAP_PWR_VAL = 0x3fc0000 # macro
PCI_EXP_DEVCAP_PWR_SCL = 0xc000000 # macro
PCI_EXP_DEVCAP_FLR = 0x10000000 # macro
PCI_EXP_DEVCTL = 8 # macro
PCI_EXP_DEVCTL_CERE = 0x0001 # macro
PCI_EXP_DEVCTL_NFERE = 0x0002 # macro
PCI_EXP_DEVCTL_FERE = 0x0004 # macro
PCI_EXP_DEVCTL_URRE = 0x0008 # macro
PCI_EXP_DEVCTL_RELAX_EN = 0x0010 # macro
PCI_EXP_DEVCTL_PAYLOAD = 0x00e0 # macro
PCI_EXP_DEVCTL_EXT_TAG = 0x0100 # macro
PCI_EXP_DEVCTL_PHANTOM = 0x0200 # macro
PCI_EXP_DEVCTL_AUX_PME = 0x0400 # macro
PCI_EXP_DEVCTL_NOSNOOP_EN = 0x0800 # macro
PCI_EXP_DEVCTL_READRQ = 0x7000 # macro
PCI_EXP_DEVCTL_BCR_FLR = 0x8000 # macro
PCI_EXP_DEVSTA = 10 # macro
PCI_EXP_DEVSTA_CED = 0x01 # macro
PCI_EXP_DEVSTA_NFED = 0x02 # macro
PCI_EXP_DEVSTA_FED = 0x04 # macro
PCI_EXP_DEVSTA_URD = 0x08 # macro
PCI_EXP_DEVSTA_AUXPD = 0x10 # macro
PCI_EXP_DEVSTA_TRPND = 0x20 # macro
PCI_EXP_LNKCAP = 12 # macro
PCI_EXP_LNKCAP_SLS = 0x0000000f # macro
PCI_EXP_LNKCAP_MLW = 0x000003f0 # macro
PCI_EXP_LNKCAP_ASPMS = 0x00000c00 # macro
PCI_EXP_LNKCAP_L0SEL = 0x00007000 # macro
PCI_EXP_LNKCAP_L1EL = 0x00038000 # macro
PCI_EXP_LNKCAP_CLKPM = 0x00040000 # macro
PCI_EXP_LNKCAP_SDERC = 0x00080000 # macro
PCI_EXP_LNKCAP_DLLLARC = 0x00100000 # macro
PCI_EXP_LNKCAP_LBNC = 0x00200000 # macro
PCI_EXP_LNKCAP_PN = 0xff000000 # macro
PCI_EXP_LNKCTL = 16 # macro
PCI_EXP_LNKCTL_ASPMC = 0x0003 # macro
PCI_EXP_LNKCTL_RCB = 0x0008 # macro
PCI_EXP_LNKCTL_LD = 0x0010 # macro
PCI_EXP_LNKCTL_RL = 0x0020 # macro
PCI_EXP_LNKCTL_CCC = 0x0040 # macro
PCI_EXP_LNKCTL_ES = 0x0080 # macro
PCI_EXP_LNKCTL_CLKREQ_EN = 0x100 # macro
PCI_EXP_LNKCTL_HAWD = 0x0200 # macro
PCI_EXP_LNKCTL_LBMIE = 0x0400 # macro
PCI_EXP_LNKCTL_LABIE = 0x0800 # macro
PCI_EXP_LNKSTA = 18 # macro
PCI_EXP_LNKSTA_CLS = 0x000f # macro
PCI_EXP_LNKSTA_CLS_2_5GB = 0x01 # macro
PCI_EXP_LNKSTA_CLS_5_0GB = 0x02 # macro
PCI_EXP_LNKSTA_NLW = 0x03f0 # macro
PCI_EXP_LNKSTA_NLW_SHIFT = 4 # macro
PCI_EXP_LNKSTA_LT = 0x0800 # macro
PCI_EXP_LNKSTA_SLC = 0x1000 # macro
PCI_EXP_LNKSTA_DLLLA = 0x2000 # macro
PCI_EXP_LNKSTA_LBMS = 0x4000 # macro
PCI_EXP_LNKSTA_LABS = 0x8000 # macro
PCI_EXP_SLTCAP = 20 # macro
PCI_EXP_SLTCAP_ABP = 0x00000001 # macro
PCI_EXP_SLTCAP_PCP = 0x00000002 # macro
PCI_EXP_SLTCAP_MRLSP = 0x00000004 # macro
PCI_EXP_SLTCAP_AIP = 0x00000008 # macro
PCI_EXP_SLTCAP_PIP = 0x00000010 # macro
PCI_EXP_SLTCAP_HPS = 0x00000020 # macro
PCI_EXP_SLTCAP_HPC = 0x00000040 # macro
PCI_EXP_SLTCAP_SPLV = 0x00007f80 # macro
PCI_EXP_SLTCAP_SPLS = 0x00018000 # macro
PCI_EXP_SLTCAP_EIP = 0x00020000 # macro
PCI_EXP_SLTCAP_NCCS = 0x00040000 # macro
PCI_EXP_SLTCAP_PSN = 0xfff80000 # macro
PCI_EXP_SLTCTL = 24 # macro
PCI_EXP_SLTCTL_ABPE = 0x0001 # macro
PCI_EXP_SLTCTL_PFDE = 0x0002 # macro
PCI_EXP_SLTCTL_MRLSCE = 0x0004 # macro
PCI_EXP_SLTCTL_PDCE = 0x0008 # macro
PCI_EXP_SLTCTL_CCIE = 0x0010 # macro
PCI_EXP_SLTCTL_HPIE = 0x0020 # macro
PCI_EXP_SLTCTL_AIC = 0x00c0 # macro
PCI_EXP_SLTCTL_PIC = 0x0300 # macro
PCI_EXP_SLTCTL_PCC = 0x0400 # macro
PCI_EXP_SLTCTL_EIC = 0x0800 # macro
PCI_EXP_SLTCTL_DLLSCE = 0x1000 # macro
PCI_EXP_SLTSTA = 26 # macro
PCI_EXP_SLTSTA_ABP = 0x0001 # macro
PCI_EXP_SLTSTA_PFD = 0x0002 # macro
PCI_EXP_SLTSTA_MRLSC = 0x0004 # macro
PCI_EXP_SLTSTA_PDC = 0x0008 # macro
PCI_EXP_SLTSTA_CC = 0x0010 # macro
PCI_EXP_SLTSTA_MRLSS = 0x0020 # macro
PCI_EXP_SLTSTA_PDS = 0x0040 # macro
PCI_EXP_SLTSTA_EIS = 0x0080 # macro
PCI_EXP_SLTSTA_DLLSC = 0x0100 # macro
PCI_EXP_RTCTL = 28 # macro
PCI_EXP_RTCTL_SECEE = 0x01 # macro
PCI_EXP_RTCTL_SENFEE = 0x02 # macro
PCI_EXP_RTCTL_SEFEE = 0x04 # macro
PCI_EXP_RTCTL_PMEIE = 0x08 # macro
PCI_EXP_RTCTL_CRSSVE = 0x10 # macro
PCI_EXP_RTCAP = 30 # macro
PCI_EXP_RTSTA = 32 # macro
PCI_EXP_DEVCAP2 = 36 # macro
PCI_EXP_DEVCAP2_ARI = 0x20 # macro
PCI_EXP_DEVCTL2 = 40 # macro
PCI_EXP_DEVCTL2_ARI = 0x20 # macro
PCI_EXP_LNKCTL2 = 48 # macro
PCI_EXP_SLTCTL2 = 56 # macro
def PCI_EXT_CAP_ID(header):  # macro
   return (header&0x0000ffff)  
def PCI_EXT_CAP_VER(header):  # macro
   return ((header>>16)&0xf)  
def PCI_EXT_CAP_NEXT(header):  # macro
   return ((header>>20)&0xffc)  
PCI_EXT_CAP_ID_ERR = 1 # macro
PCI_EXT_CAP_ID_VC = 2 # macro
PCI_EXT_CAP_ID_DSN = 3 # macro
PCI_EXT_CAP_ID_PWR = 4 # macro
PCI_EXT_CAP_ID_ARI = 14 # macro
PCI_EXT_CAP_ID_ATS = 15 # macro
PCI_EXT_CAP_ID_SRIOV = 16 # macro
PCI_ERR_UNCOR_STATUS = 4 # macro
PCI_ERR_UNC_TRAIN = 0x00000001 # macro
PCI_ERR_UNC_DLP = 0x00000010 # macro
PCI_ERR_UNC_POISON_TLP = 0x00001000 # macro
PCI_ERR_UNC_FCP = 0x00002000 # macro
PCI_ERR_UNC_COMP_TIME = 0x00004000 # macro
PCI_ERR_UNC_COMP_ABORT = 0x00008000 # macro
PCI_ERR_UNC_UNX_COMP = 0x00010000 # macro
PCI_ERR_UNC_RX_OVER = 0x00020000 # macro
PCI_ERR_UNC_MALF_TLP = 0x00040000 # macro
PCI_ERR_UNC_ECRC = 0x00080000 # macro
PCI_ERR_UNC_UNSUP = 0x00100000 # macro
PCI_ERR_UNCOR_MASK = 8 # macro
PCI_ERR_UNCOR_SEVER = 12 # macro
PCI_ERR_COR_STATUS = 16 # macro
PCI_ERR_COR_RCVR = 0x00000001 # macro
PCI_ERR_COR_BAD_TLP = 0x00000040 # macro
PCI_ERR_COR_BAD_DLLP = 0x00000080 # macro
PCI_ERR_COR_REP_ROLL = 0x00000100 # macro
PCI_ERR_COR_REP_TIMER = 0x00001000 # macro
PCI_ERR_COR_MASK = 20 # macro
PCI_ERR_CAP = 24 # macro
def PCI_ERR_CAP_FEP(x):  # macro
   return ((x)&31)  
PCI_ERR_CAP_ECRC_GENC = 0x00000020 # macro
PCI_ERR_CAP_ECRC_GENE = 0x00000040 # macro
PCI_ERR_CAP_ECRC_CHKC = 0x00000080 # macro
PCI_ERR_CAP_ECRC_CHKE = 0x00000100 # macro
PCI_ERR_HEADER_LOG = 28 # macro
PCI_ERR_ROOT_COMMAND = 44 # macro
PCI_ERR_ROOT_CMD_COR_EN = 0x00000001 # macro
PCI_ERR_ROOT_CMD_NONFATAL_EN = 0x00000002 # macro
PCI_ERR_ROOT_CMD_FATAL_EN = 0x00000004 # macro
PCI_ERR_ROOT_STATUS = 48 # macro
PCI_ERR_ROOT_COR_RCV = 0x00000001 # macro
PCI_ERR_ROOT_MULTI_COR_RCV = 0x00000002 # macro
PCI_ERR_ROOT_UNCOR_RCV = 0x00000004 # macro
PCI_ERR_ROOT_MULTI_UNCOR_RCV = 0x00000008 # macro
PCI_ERR_ROOT_FIRST_FATAL = 0x00000010 # macro
PCI_ERR_ROOT_NONFATAL_RCV = 0x00000020 # macro
PCI_ERR_ROOT_FATAL_RCV = 0x00000040 # macro
PCI_ERR_ROOT_COR_SRC = 52 # macro
PCI_ERR_ROOT_SRC = 54 # macro
PCI_VC_PORT_REG1 = 4 # macro
PCI_VC_PORT_REG2 = 8 # macro
PCI_VC_PORT_CTRL = 12 # macro
PCI_VC_PORT_STATUS = 14 # macro
PCI_VC_RES_CAP = 16 # macro
PCI_VC_RES_CTRL = 20 # macro
PCI_VC_RES_STATUS = 26 # macro
PCI_PWR_DSR = 4 # macro
PCI_PWR_DATA = 8 # macro
def PCI_PWR_DATA_BASE(x):  # macro
   return ((x)&0xff)  
def PCI_PWR_DATA_SCALE(x):  # macro
   return (((x)>>8)&3)  
def PCI_PWR_DATA_PM_SUB(x):  # macro
   return (((x)>>10)&7)  
def PCI_PWR_DATA_PM_STATE(x):  # macro
   return (((x)>>13)&3)  
def PCI_PWR_DATA_TYPE(x):  # macro
   return (((x)>>15)&7)  
def PCI_PWR_DATA_RAIL(x):  # macro
   return (((x)>>18)&7)  
PCI_PWR_CAP = 12 # macro
def PCI_PWR_CAP_BUDGET(x):  # macro
   return ((x)&1)  
HT_3BIT_CAP_MASK = 0xE0 # macro
HT_CAPTYPE_SLAVE = 0x00 # macro
HT_CAPTYPE_HOST = 0x20 # macro
HT_5BIT_CAP_MASK = 0xF8 # macro
HT_CAPTYPE_IRQ = 0x80 # macro
HT_CAPTYPE_REMAPPING_40 = 0xA0 # macro
HT_CAPTYPE_REMAPPING_64 = 0xA2 # macro
HT_CAPTYPE_UNITID_CLUMP = 0x90 # macro
HT_CAPTYPE_EXTCONF = 0x98 # macro
HT_CAPTYPE_MSI_MAPPING = 0xA8 # macro
HT_MSI_FLAGS = 0x02 # macro
HT_MSI_FLAGS_ENABLE = 0x1 # macro
HT_MSI_FLAGS_FIXED = 0x2 # macro
HT_MSI_FIXED_ADDR = 0x00000000FEE00000 # macro
HT_MSI_ADDR_LO = 0x04 # macro
HT_MSI_ADDR_LO_MASK = 0xFFF00000 # macro
HT_MSI_ADDR_HI = 0x08 # macro
HT_CAPTYPE_DIRECT_ROUTE = 0xB0 # macro
HT_CAPTYPE_VCSET = 0xB8 # macro
HT_CAPTYPE_ERROR_RETRY = 0xC0 # macro
HT_CAPTYPE_GEN3 = 0xD0 # macro
HT_CAPTYPE_PM = 0xE0 # macro
PCI_ARI_CAP = 0x04 # macro
PCI_ARI_CAP_MFVC = 0x0001 # macro
PCI_ARI_CAP_ACS = 0x0002 # macro
def PCI_ARI_CAP_NFN(x):  # macro
   return (((x)>>8)&0xff)  
PCI_ARI_CTRL = 0x06 # macro
PCI_ARI_CTRL_MFVC = 0x0001 # macro
PCI_ARI_CTRL_ACS = 0x0002 # macro
def PCI_ARI_CTRL_FG(x):  # macro
   return (((x)>>4)&7)  
PCI_ATS_CAP = 0x04 # macro
def PCI_ATS_CAP_QDEP(x):  # macro
   return ((x)&0x1f)  
PCI_ATS_MAX_QDEP = 32 # macro
PCI_ATS_CTRL = 0x06 # macro
PCI_ATS_CTRL_ENABLE = 0x8000 # macro
def PCI_ATS_CTRL_STU(x):  # macro
   return ((x)&0x1f)  
PCI_ATS_MIN_STU = 12 # macro
PCI_SRIOV_CAP = 0x04 # macro
PCI_SRIOV_CAP_VFM = 0x01 # macro
def PCI_SRIOV_CAP_INTR(x):  # macro
   return ((x)>>21)  
PCI_SRIOV_CTRL = 0x08 # macro
PCI_SRIOV_CTRL_VFE = 0x01 # macro
PCI_SRIOV_CTRL_VFM = 0x02 # macro
PCI_SRIOV_CTRL_INTR = 0x04 # macro
PCI_SRIOV_CTRL_MSE = 0x08 # macro
PCI_SRIOV_CTRL_ARI = 0x10 # macro
PCI_SRIOV_STATUS = 0x0a # macro
PCI_SRIOV_STATUS_VFM = 0x01 # macro
PCI_SRIOV_INITIAL_VF = 0x0c # macro
PCI_SRIOV_TOTAL_VF = 0x0e # macro
PCI_SRIOV_NUM_VF = 0x10 # macro
PCI_SRIOV_FUNC_LINK = 0x12 # macro
PCI_SRIOV_VF_OFFSET = 0x14 # macro
PCI_SRIOV_VF_STRIDE = 0x16 # macro
PCI_SRIOV_VF_DID = 0x1a # macro
PCI_SRIOV_SUP_PGSIZE = 0x1c # macro
PCI_SRIOV_SYS_PGSIZE = 0x20 # macro
PCI_SRIOV_BAR = 0x24 # macro
PCI_SRIOV_NUM_BARS = 6 # macro
PCI_SRIOV_VFM = 0x3c # macro
def PCI_SRIOV_VFM_BIR(x):  # macro
   return ((x)&7)  
def PCI_SRIOV_VFM_OFFSET(x):  # macro
   return ((x)&~7)  
PCI_SRIOV_VFM_UA = 0x0 # macro
PCI_SRIOV_VFM_MI = 0x1 # macro
PCI_SRIOV_VFM_MO = 0x2 # macro
PCI_SRIOV_VFM_AV = 0x3 # macro
__all__ = \
    ['HT_3BIT_CAP_MASK', 'HT_5BIT_CAP_MASK',
    'HT_CAPTYPE_DIRECT_ROUTE', 'HT_CAPTYPE_ERROR_RETRY',
    'HT_CAPTYPE_EXTCONF', 'HT_CAPTYPE_GEN3', 'HT_CAPTYPE_HOST',
    'HT_CAPTYPE_IRQ', 'HT_CAPTYPE_MSI_MAPPING', 'HT_CAPTYPE_PM',
    'HT_CAPTYPE_REMAPPING_40', 'HT_CAPTYPE_REMAPPING_64',
    'HT_CAPTYPE_SLAVE', 'HT_CAPTYPE_UNITID_CLUMP', 'HT_CAPTYPE_VCSET',
    'HT_MSI_ADDR_HI', 'HT_MSI_ADDR_LO', 'HT_MSI_ADDR_LO_MASK',
    'HT_MSI_FIXED_ADDR', 'HT_MSI_FLAGS', 'HT_MSI_FLAGS_ENABLE',
    'HT_MSI_FLAGS_FIXED', 'LINUX_PCI_REGS_H', 'PCI_AF_CAP',
    'PCI_AF_CAP_FLR', 'PCI_AF_CAP_TP', 'PCI_AF_CTRL',
    'PCI_AF_CTRL_FLR', 'PCI_AF_LENGTH', 'PCI_AF_STATUS',
    'PCI_AF_STATUS_TP', 'PCI_AGP_COMMAND', 'PCI_AGP_COMMAND_64BIT',
    'PCI_AGP_COMMAND_AGP', 'PCI_AGP_COMMAND_FW',
    'PCI_AGP_COMMAND_RATE1', 'PCI_AGP_COMMAND_RATE2',
    'PCI_AGP_COMMAND_RATE4', 'PCI_AGP_COMMAND_RQ_MASK',
    'PCI_AGP_COMMAND_SBA', 'PCI_AGP_RFU', 'PCI_AGP_SIZEOF',
    'PCI_AGP_STATUS', 'PCI_AGP_STATUS_64BIT', 'PCI_AGP_STATUS_FW',
    'PCI_AGP_STATUS_RATE1', 'PCI_AGP_STATUS_RATE2',
    'PCI_AGP_STATUS_RATE4', 'PCI_AGP_STATUS_RQ_MASK',
    'PCI_AGP_STATUS_SBA', 'PCI_AGP_VERSION', 'PCI_ARI_CAP',
    'PCI_ARI_CAP_ACS', 'PCI_ARI_CAP_MFVC', 'PCI_ARI_CTRL',
    'PCI_ARI_CTRL_ACS', 'PCI_ARI_CTRL_MFVC', 'PCI_ATS_CAP',
    'PCI_ATS_CTRL', 'PCI_ATS_CTRL_ENABLE', 'PCI_ATS_MAX_QDEP',
    'PCI_ATS_MIN_STU', 'PCI_BASE_ADDRESS_0', 'PCI_BASE_ADDRESS_1',
    'PCI_BASE_ADDRESS_2', 'PCI_BASE_ADDRESS_3', 'PCI_BASE_ADDRESS_4',
    'PCI_BASE_ADDRESS_5', 'PCI_BASE_ADDRESS_IO_MASK',
    'PCI_BASE_ADDRESS_MEM_MASK', 'PCI_BASE_ADDRESS_MEM_PREFETCH',
    'PCI_BASE_ADDRESS_MEM_TYPE_1M', 'PCI_BASE_ADDRESS_MEM_TYPE_32',
    'PCI_BASE_ADDRESS_MEM_TYPE_64', 'PCI_BASE_ADDRESS_MEM_TYPE_MASK',
    'PCI_BASE_ADDRESS_SPACE', 'PCI_BASE_ADDRESS_SPACE_IO',
    'PCI_BASE_ADDRESS_SPACE_MEMORY', 'PCI_BIST', 'PCI_BIST_CAPABLE',
    'PCI_BIST_CODE_MASK', 'PCI_BIST_START', 'PCI_BRIDGE_CONTROL',
    'PCI_BRIDGE_CTL_BUS_RESET', 'PCI_BRIDGE_CTL_FAST_BACK',
    'PCI_BRIDGE_CTL_ISA', 'PCI_BRIDGE_CTL_MASTER_ABORT',
    'PCI_BRIDGE_CTL_PARITY', 'PCI_BRIDGE_CTL_SERR',
    'PCI_BRIDGE_CTL_VGA', 'PCI_CACHE_LINE_SIZE',
    'PCI_CAPABILITY_LIST', 'PCI_CAP_FLAGS', 'PCI_CAP_ID_AF',
    'PCI_CAP_ID_AGP', 'PCI_CAP_ID_AGP3', 'PCI_CAP_ID_CCRC',
    'PCI_CAP_ID_CHSWP', 'PCI_CAP_ID_DBG', 'PCI_CAP_ID_EXP',
    'PCI_CAP_ID_HT', 'PCI_CAP_ID_MSI', 'PCI_CAP_ID_MSIX',
    'PCI_CAP_ID_PCIX', 'PCI_CAP_ID_PM', 'PCI_CAP_ID_SHPC',
    'PCI_CAP_ID_SLOTID', 'PCI_CAP_ID_SSVID', 'PCI_CAP_ID_VNDR',
    'PCI_CAP_ID_VPD', 'PCI_CAP_LIST_ID', 'PCI_CAP_LIST_NEXT',
    'PCI_CAP_SIZEOF', 'PCI_CARDBUS_CIS', 'PCI_CB_BRIDGE_CONTROL',
    'PCI_CB_BRIDGE_CTL_16BIT_INT', 'PCI_CB_BRIDGE_CTL_CB_RESET',
    'PCI_CB_BRIDGE_CTL_ISA', 'PCI_CB_BRIDGE_CTL_MASTER_ABORT',
    'PCI_CB_BRIDGE_CTL_PARITY', 'PCI_CB_BRIDGE_CTL_POST_WRITES',
    'PCI_CB_BRIDGE_CTL_PREFETCH_MEM0',
    'PCI_CB_BRIDGE_CTL_PREFETCH_MEM1', 'PCI_CB_BRIDGE_CTL_SERR',
    'PCI_CB_BRIDGE_CTL_VGA', 'PCI_CB_CAPABILITY_LIST',
    'PCI_CB_CARD_BUS', 'PCI_CB_IO_BASE_0', 'PCI_CB_IO_BASE_0_HI',
    'PCI_CB_IO_BASE_1', 'PCI_CB_IO_BASE_1_HI', 'PCI_CB_IO_LIMIT_0',
    'PCI_CB_IO_LIMIT_0_HI', 'PCI_CB_IO_LIMIT_1',
    'PCI_CB_IO_LIMIT_1_HI', 'PCI_CB_IO_RANGE_MASK',
    'PCI_CB_LATENCY_TIMER', 'PCI_CB_LEGACY_MODE_BASE',
    'PCI_CB_MEMORY_BASE_0', 'PCI_CB_MEMORY_BASE_1',
    'PCI_CB_MEMORY_LIMIT_0', 'PCI_CB_MEMORY_LIMIT_1',
    'PCI_CB_PRIMARY_BUS', 'PCI_CB_SEC_STATUS',
    'PCI_CB_SUBORDINATE_BUS', 'PCI_CB_SUBSYSTEM_ID',
    'PCI_CB_SUBSYSTEM_VENDOR_ID', 'PCI_CHSWP_CSR', 'PCI_CHSWP_DHA',
    'PCI_CHSWP_EIM', 'PCI_CHSWP_EXT', 'PCI_CHSWP_INS',
    'PCI_CHSWP_LOO', 'PCI_CHSWP_PI', 'PCI_CHSWP_PIE',
    'PCI_CLASS_DEVICE', 'PCI_CLASS_PROG', 'PCI_CLASS_REVISION',
    'PCI_COMMAND', 'PCI_COMMAND_FAST_BACK',
    'PCI_COMMAND_INTX_DISABLE', 'PCI_COMMAND_INVALIDATE',
    'PCI_COMMAND_IO', 'PCI_COMMAND_MASTER', 'PCI_COMMAND_MEMORY',
    'PCI_COMMAND_PARITY', 'PCI_COMMAND_SERR', 'PCI_COMMAND_SPECIAL',
    'PCI_COMMAND_VGA_PALETTE', 'PCI_COMMAND_WAIT', 'PCI_DEVICE_ID',
    'PCI_ERR_CAP', 'PCI_ERR_CAP_ECRC_CHKC', 'PCI_ERR_CAP_ECRC_CHKE',
    'PCI_ERR_CAP_ECRC_GENC', 'PCI_ERR_CAP_ECRC_GENE',
    'PCI_ERR_COR_BAD_DLLP', 'PCI_ERR_COR_BAD_TLP', 'PCI_ERR_COR_MASK',
    'PCI_ERR_COR_RCVR', 'PCI_ERR_COR_REP_ROLL',
    'PCI_ERR_COR_REP_TIMER', 'PCI_ERR_COR_STATUS',
    'PCI_ERR_HEADER_LOG', 'PCI_ERR_ROOT_CMD_COR_EN',
    'PCI_ERR_ROOT_CMD_FATAL_EN', 'PCI_ERR_ROOT_CMD_NONFATAL_EN',
    'PCI_ERR_ROOT_COMMAND', 'PCI_ERR_ROOT_COR_RCV',
    'PCI_ERR_ROOT_COR_SRC', 'PCI_ERR_ROOT_FATAL_RCV',
    'PCI_ERR_ROOT_FIRST_FATAL', 'PCI_ERR_ROOT_MULTI_COR_RCV',
    'PCI_ERR_ROOT_MULTI_UNCOR_RCV', 'PCI_ERR_ROOT_NONFATAL_RCV',
    'PCI_ERR_ROOT_SRC', 'PCI_ERR_ROOT_STATUS',
    'PCI_ERR_ROOT_UNCOR_RCV', 'PCI_ERR_UNCOR_MASK',
    'PCI_ERR_UNCOR_SEVER', 'PCI_ERR_UNCOR_STATUS',
    'PCI_ERR_UNC_COMP_ABORT', 'PCI_ERR_UNC_COMP_TIME',
    'PCI_ERR_UNC_DLP', 'PCI_ERR_UNC_ECRC', 'PCI_ERR_UNC_FCP',
    'PCI_ERR_UNC_MALF_TLP', 'PCI_ERR_UNC_POISON_TLP',
    'PCI_ERR_UNC_RX_OVER', 'PCI_ERR_UNC_TRAIN', 'PCI_ERR_UNC_UNSUP',
    'PCI_ERR_UNC_UNX_COMP', 'PCI_EXP_DEVCAP', 'PCI_EXP_DEVCAP2',
    'PCI_EXP_DEVCAP2_ARI', 'PCI_EXP_DEVCAP_ATN_BUT',
    'PCI_EXP_DEVCAP_ATN_IND', 'PCI_EXP_DEVCAP_EXT_TAG',
    'PCI_EXP_DEVCAP_FLR', 'PCI_EXP_DEVCAP_L0S', 'PCI_EXP_DEVCAP_L1',
    'PCI_EXP_DEVCAP_PAYLOAD', 'PCI_EXP_DEVCAP_PHANTOM',
    'PCI_EXP_DEVCAP_PWR_IND', 'PCI_EXP_DEVCAP_PWR_SCL',
    'PCI_EXP_DEVCAP_PWR_VAL', 'PCI_EXP_DEVCAP_RBER', 'PCI_EXP_DEVCTL',
    'PCI_EXP_DEVCTL2', 'PCI_EXP_DEVCTL2_ARI',
    'PCI_EXP_DEVCTL_AUX_PME', 'PCI_EXP_DEVCTL_BCR_FLR',
    'PCI_EXP_DEVCTL_CERE', 'PCI_EXP_DEVCTL_EXT_TAG',
    'PCI_EXP_DEVCTL_FERE', 'PCI_EXP_DEVCTL_NFERE',
    'PCI_EXP_DEVCTL_NOSNOOP_EN', 'PCI_EXP_DEVCTL_PAYLOAD',
    'PCI_EXP_DEVCTL_PHANTOM', 'PCI_EXP_DEVCTL_READRQ',
    'PCI_EXP_DEVCTL_RELAX_EN', 'PCI_EXP_DEVCTL_URRE',
    'PCI_EXP_DEVSTA', 'PCI_EXP_DEVSTA_AUXPD', 'PCI_EXP_DEVSTA_CED',
    'PCI_EXP_DEVSTA_FED', 'PCI_EXP_DEVSTA_NFED',
    'PCI_EXP_DEVSTA_TRPND', 'PCI_EXP_DEVSTA_URD', 'PCI_EXP_FLAGS',
    'PCI_EXP_FLAGS_IRQ', 'PCI_EXP_FLAGS_SLOT', 'PCI_EXP_FLAGS_TYPE',
    'PCI_EXP_FLAGS_VERS', 'PCI_EXP_LNKCAP', 'PCI_EXP_LNKCAP_ASPMS',
    'PCI_EXP_LNKCAP_CLKPM', 'PCI_EXP_LNKCAP_DLLLARC',
    'PCI_EXP_LNKCAP_L0SEL', 'PCI_EXP_LNKCAP_L1EL',
    'PCI_EXP_LNKCAP_LBNC', 'PCI_EXP_LNKCAP_MLW', 'PCI_EXP_LNKCAP_PN',
    'PCI_EXP_LNKCAP_SDERC', 'PCI_EXP_LNKCAP_SLS', 'PCI_EXP_LNKCTL',
    'PCI_EXP_LNKCTL2', 'PCI_EXP_LNKCTL_ASPMC', 'PCI_EXP_LNKCTL_CCC',
    'PCI_EXP_LNKCTL_CLKREQ_EN', 'PCI_EXP_LNKCTL_ES',
    'PCI_EXP_LNKCTL_HAWD', 'PCI_EXP_LNKCTL_LABIE',
    'PCI_EXP_LNKCTL_LBMIE', 'PCI_EXP_LNKCTL_LD', 'PCI_EXP_LNKCTL_RCB',
    'PCI_EXP_LNKCTL_RL', 'PCI_EXP_LNKSTA', 'PCI_EXP_LNKSTA_CLS',
    'PCI_EXP_LNKSTA_CLS_2_5GB', 'PCI_EXP_LNKSTA_CLS_5_0GB',
    'PCI_EXP_LNKSTA_DLLLA', 'PCI_EXP_LNKSTA_LABS',
    'PCI_EXP_LNKSTA_LBMS', 'PCI_EXP_LNKSTA_LT', 'PCI_EXP_LNKSTA_NLW',
    'PCI_EXP_LNKSTA_NLW_SHIFT', 'PCI_EXP_LNKSTA_SLC', 'PCI_EXP_RTCAP',
    'PCI_EXP_RTCTL', 'PCI_EXP_RTCTL_CRSSVE', 'PCI_EXP_RTCTL_PMEIE',
    'PCI_EXP_RTCTL_SECEE', 'PCI_EXP_RTCTL_SEFEE',
    'PCI_EXP_RTCTL_SENFEE', 'PCI_EXP_RTSTA', 'PCI_EXP_SLTCAP',
    'PCI_EXP_SLTCAP_ABP', 'PCI_EXP_SLTCAP_AIP', 'PCI_EXP_SLTCAP_EIP',
    'PCI_EXP_SLTCAP_HPC', 'PCI_EXP_SLTCAP_HPS',
    'PCI_EXP_SLTCAP_MRLSP', 'PCI_EXP_SLTCAP_NCCS',
    'PCI_EXP_SLTCAP_PCP', 'PCI_EXP_SLTCAP_PIP', 'PCI_EXP_SLTCAP_PSN',
    'PCI_EXP_SLTCAP_SPLS', 'PCI_EXP_SLTCAP_SPLV', 'PCI_EXP_SLTCTL',
    'PCI_EXP_SLTCTL2', 'PCI_EXP_SLTCTL_ABPE', 'PCI_EXP_SLTCTL_AIC',
    'PCI_EXP_SLTCTL_CCIE', 'PCI_EXP_SLTCTL_DLLSCE',
    'PCI_EXP_SLTCTL_EIC', 'PCI_EXP_SLTCTL_HPIE',
    'PCI_EXP_SLTCTL_MRLSCE', 'PCI_EXP_SLTCTL_PCC',
    'PCI_EXP_SLTCTL_PDCE', 'PCI_EXP_SLTCTL_PFDE',
    'PCI_EXP_SLTCTL_PIC', 'PCI_EXP_SLTSTA', 'PCI_EXP_SLTSTA_ABP',
    'PCI_EXP_SLTSTA_CC', 'PCI_EXP_SLTSTA_DLLSC', 'PCI_EXP_SLTSTA_EIS',
    'PCI_EXP_SLTSTA_MRLSC', 'PCI_EXP_SLTSTA_MRLSS',
    'PCI_EXP_SLTSTA_PDC', 'PCI_EXP_SLTSTA_PDS', 'PCI_EXP_SLTSTA_PFD',
    'PCI_EXP_TYPE_DOWNSTREAM', 'PCI_EXP_TYPE_ENDPOINT',
    'PCI_EXP_TYPE_LEG_END', 'PCI_EXP_TYPE_PCI_BRIDGE',
    'PCI_EXP_TYPE_RC_EC', 'PCI_EXP_TYPE_RC_END',
    'PCI_EXP_TYPE_ROOT_PORT', 'PCI_EXP_TYPE_UPSTREAM',
    'PCI_EXT_CAP_ID_ARI', 'PCI_EXT_CAP_ID_ATS', 'PCI_EXT_CAP_ID_DSN',
    'PCI_EXT_CAP_ID_ERR', 'PCI_EXT_CAP_ID_PWR',
    'PCI_EXT_CAP_ID_SRIOV', 'PCI_EXT_CAP_ID_VC', 'PCI_HEADER_TYPE',
    'PCI_HEADER_TYPE_BRIDGE', 'PCI_HEADER_TYPE_CARDBUS',
    'PCI_HEADER_TYPE_NORMAL', 'PCI_INTERRUPT_LINE',
    'PCI_INTERRUPT_PIN', 'PCI_IO_BASE', 'PCI_IO_BASE_UPPER16',
    'PCI_IO_LIMIT', 'PCI_IO_LIMIT_UPPER16', 'PCI_IO_RANGE_MASK',
    'PCI_IO_RANGE_TYPE_16', 'PCI_IO_RANGE_TYPE_32',
    'PCI_IO_RANGE_TYPE_MASK', 'PCI_LATENCY_TIMER', 'PCI_MAX_LAT',
    'PCI_MEMORY_BASE', 'PCI_MEMORY_LIMIT', 'PCI_MEMORY_RANGE_MASK',
    'PCI_MEMORY_RANGE_TYPE_MASK', 'PCI_MIN_GNT', 'PCI_MSIX_FLAGS',
    'PCI_MSIX_FLAGS_BIRMASK', 'PCI_MSIX_FLAGS_ENABLE',
    'PCI_MSIX_FLAGS_MASKALL', 'PCI_MSIX_FLAGS_QSIZE',
    'PCI_MSI_ADDRESS_HI', 'PCI_MSI_ADDRESS_LO', 'PCI_MSI_DATA_32',
    'PCI_MSI_DATA_64', 'PCI_MSI_FLAGS', 'PCI_MSI_FLAGS_64BIT',
    'PCI_MSI_FLAGS_ENABLE', 'PCI_MSI_FLAGS_MASKBIT',
    'PCI_MSI_FLAGS_QMASK', 'PCI_MSI_FLAGS_QSIZE', 'PCI_MSI_MASK_32',
    'PCI_MSI_MASK_64', 'PCI_MSI_RFU', 'PCI_PM_BPCC_ENABLE',
    'PCI_PM_CAP_AUX_POWER', 'PCI_PM_CAP_D1', 'PCI_PM_CAP_D2',
    'PCI_PM_CAP_DSI', 'PCI_PM_CAP_PME', 'PCI_PM_CAP_PME_CLOCK',
    'PCI_PM_CAP_PME_D0', 'PCI_PM_CAP_PME_D1', 'PCI_PM_CAP_PME_D2',
    'PCI_PM_CAP_PME_D3', 'PCI_PM_CAP_PME_D3cold',
    'PCI_PM_CAP_PME_MASK', 'PCI_PM_CAP_PME_SHIFT',
    'PCI_PM_CAP_RESERVED', 'PCI_PM_CAP_VER_MASK', 'PCI_PM_CTRL',
    'PCI_PM_CTRL_DATA_SCALE_MASK', 'PCI_PM_CTRL_DATA_SEL_MASK',
    'PCI_PM_CTRL_NO_SOFT_RESET', 'PCI_PM_CTRL_PME_ENABLE',
    'PCI_PM_CTRL_PME_STATUS', 'PCI_PM_CTRL_STATE_MASK',
    'PCI_PM_DATA_REGISTER', 'PCI_PM_PMC', 'PCI_PM_PPB_B2_B3',
    'PCI_PM_PPB_EXTENSIONS', 'PCI_PM_SIZEOF', 'PCI_PREF_BASE_UPPER32',
    'PCI_PREF_LIMIT_UPPER32', 'PCI_PREF_MEMORY_BASE',
    'PCI_PREF_MEMORY_LIMIT', 'PCI_PREF_RANGE_MASK',
    'PCI_PREF_RANGE_TYPE_32', 'PCI_PREF_RANGE_TYPE_64',
    'PCI_PREF_RANGE_TYPE_MASK', 'PCI_PRIMARY_BUS', 'PCI_PWR_CAP',
    'PCI_PWR_DATA', 'PCI_PWR_DSR', 'PCI_REVISION_ID',
    'PCI_ROM_ADDRESS', 'PCI_ROM_ADDRESS1', 'PCI_ROM_ADDRESS_ENABLE',
    'PCI_ROM_ADDRESS_MASK', 'PCI_SECONDARY_BUS',
    'PCI_SEC_LATENCY_TIMER', 'PCI_SEC_STATUS', 'PCI_SID_CHASSIS_NR',
    'PCI_SID_ESR', 'PCI_SID_ESR_FIC', 'PCI_SID_ESR_NSLOTS',
    'PCI_SRIOV_BAR', 'PCI_SRIOV_CAP', 'PCI_SRIOV_CAP_VFM',
    'PCI_SRIOV_CTRL', 'PCI_SRIOV_CTRL_ARI', 'PCI_SRIOV_CTRL_INTR',
    'PCI_SRIOV_CTRL_MSE', 'PCI_SRIOV_CTRL_VFE', 'PCI_SRIOV_CTRL_VFM',
    'PCI_SRIOV_FUNC_LINK', 'PCI_SRIOV_INITIAL_VF',
    'PCI_SRIOV_NUM_BARS', 'PCI_SRIOV_NUM_VF', 'PCI_SRIOV_STATUS',
    'PCI_SRIOV_STATUS_VFM', 'PCI_SRIOV_SUP_PGSIZE',
    'PCI_SRIOV_SYS_PGSIZE', 'PCI_SRIOV_TOTAL_VF', 'PCI_SRIOV_VFM',
    'PCI_SRIOV_VFM_AV', 'PCI_SRIOV_VFM_MI', 'PCI_SRIOV_VFM_MO',
    'PCI_SRIOV_VFM_UA', 'PCI_SRIOV_VF_DID', 'PCI_SRIOV_VF_OFFSET',
    'PCI_SRIOV_VF_STRIDE', 'PCI_STATUS', 'PCI_STATUS_66MHZ',
    'PCI_STATUS_CAP_LIST', 'PCI_STATUS_DETECTED_PARITY',
    'PCI_STATUS_DEVSEL_FAST', 'PCI_STATUS_DEVSEL_MASK',
    'PCI_STATUS_DEVSEL_MEDIUM', 'PCI_STATUS_DEVSEL_SLOW',
    'PCI_STATUS_FAST_BACK', 'PCI_STATUS_INTERRUPT',
    'PCI_STATUS_PARITY', 'PCI_STATUS_REC_MASTER_ABORT',
    'PCI_STATUS_REC_TARGET_ABORT', 'PCI_STATUS_SIG_SYSTEM_ERROR',
    'PCI_STATUS_SIG_TARGET_ABORT', 'PCI_STATUS_UDF',
    'PCI_SUBORDINATE_BUS', 'PCI_SUBSYSTEM_ID',
    'PCI_SUBSYSTEM_VENDOR_ID', 'PCI_VC_PORT_CTRL', 'PCI_VC_PORT_REG1',
    'PCI_VC_PORT_REG2', 'PCI_VC_PORT_STATUS', 'PCI_VC_RES_CAP',
    'PCI_VC_RES_CTRL', 'PCI_VC_RES_STATUS', 'PCI_VENDOR_ID',
    'PCI_VPD_ADDR', 'PCI_VPD_ADDR_F', 'PCI_VPD_ADDR_MASK',
    'PCI_VPD_DATA', 'PCI_X_CMD', 'PCI_X_CMD_DPERR_E', 'PCI_X_CMD_ERO',
    'PCI_X_CMD_MAX_READ', 'PCI_X_CMD_MAX_SPLIT', 'PCI_X_CMD_READ_1K',
    'PCI_X_CMD_READ_2K', 'PCI_X_CMD_READ_4K', 'PCI_X_CMD_READ_512',
    'PCI_X_CMD_SPLIT_1', 'PCI_X_CMD_SPLIT_12', 'PCI_X_CMD_SPLIT_16',
    'PCI_X_CMD_SPLIT_2', 'PCI_X_CMD_SPLIT_3', 'PCI_X_CMD_SPLIT_32',
    'PCI_X_CMD_SPLIT_4', 'PCI_X_CMD_SPLIT_8', 'PCI_X_STATUS',
    'PCI_X_STATUS_133MHZ', 'PCI_X_STATUS_266MHZ',
    'PCI_X_STATUS_533MHZ', 'PCI_X_STATUS_64BIT', 'PCI_X_STATUS_BUS',
    'PCI_X_STATUS_COMPLEX', 'PCI_X_STATUS_DEVFN',
    'PCI_X_STATUS_MAX_CUM', 'PCI_X_STATUS_MAX_READ',
    'PCI_X_STATUS_MAX_SPLIT', 'PCI_X_STATUS_SPL_DISC',
    'PCI_X_STATUS_SPL_ERR', 'PCI_X_STATUS_UNX_SPL']
