name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testmetal:
    name: Metal Tests
    runs-on: macos-13
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: pip install -e '.[metal,testing]'
    - name: Test LLaMA compile speed
      run: PYTHONPATH="." METAL=1 python3 test/external/external_test_speed_llama.py
    #- name: Run dtype test
    #  run: DEBUG=4 METAL=1 python -m pytest test/test_dtype.py
    - name: Run ops test
      run: DEBUG=2 METAL=1 python -m pytest test/test_ops.py
    # dtype test has issues on test_half_to_int8